---
- name: configures default user (cloud-init)
  command: >
    /usr/sbin/qm
    set {{ item.value.vmid }}
    --ciuser {{ item.value.user }}
  changed_when: no
  loop: "{{ query('dict', proxmox_vms) }}"
  when:
    - item.value.vmid is defined
    - item.value.user is defined
    - item.value.user != ''

- name: configure password for default user  (cloud-init)
  command: >
    /usr/sbin/qm
    set {{ item.value.vmid }}
    --cipassword {{ item.value.password }}
  changed_when: no
  loop: "{{ query('dict', proxmox_vms) }}"
  when:
    - item.value.vmid is defined
    - item.value.password is defined
    - item.value.password != ''

- name: configure dns (cloud-init)
  command: >
    /usr/sbin/qm
    set {{ item.value.vmid }}
    --nameserver {{ item.value.dns | join(',') }}
  changed_when: no
  loop: "{{ query('dict', proxmox_vms) }}"
  when:
    - item.value.vmid is defined
    - item.value.dns is defined
    - item.value.dns | length > 0

- name: configure searchdomain (cloud-init)
  command: >
    /usr/sbin/qm
    set {{ item.value.vmid }}
    --searchdomain {{ item.value.domain }}
  changed_when: no
  loop: "{{ query('dict', proxmox_vms) }}"
  when:
    - item.value.vmid is defined
    - item.value.domain is defined
    - item.value.domain != ''

- name: configure network for net0 (cloud-init)
  command: >
    /usr/sbin/qm
    set {{ item.value.vmid }}
    --ipconfig0 ip={{ item.value.ip }},gw={{ item.value.gateway }}
  changed_when: no
  loop: "{{ query('dict', proxmox_vms) }}"
  when:
    - item.value.vmid is defined
    - item.value.ip is defined
    - item.value.gateway is defined

- name: configure ssh key for default user (cloud-init)
  command: >
    /usr/sbin/qm
    set {{ item.value.vmid }}
    --sshkeys=/tmp/{{ item.value.vmid }}.pub
  changed_when: no
  loop: "{{ query('dict', proxmox_vms) }}"
  when:
    - item.value.vmid
    - item.value.ssh_key is defined
